### ISSUE TITLE
全体管理

### ISSUE THREAD

**Issue by yusukegunji** [camp-team/school-potal#63]
## 画面一覧

- [x] トップ画面/home #64 
- [x] 記事詳細画面/article-detail #65 
- [x] 関連記事画面/article-relation #61 
- [x] admin管理画面/editor #66 
- [x] 生徒もっと見る画面（ダイアログ）/members-dialog #62 
- [x] 先生もっと見る画面（ダイアログ）/teachers-dialog #67 
- [x] 利用規約画面/rule #16 
- [x] プライバシー画面/privacy #68 
- [x] 特商法画面/legal #17 
- [x] サイドナビ画面（フッター込み）/sidenav #69 
- [x] ヘッダー画面/header #70 
- [x] DM送信画面（ダイアログ）/dm-dialog #74 
- [x] 404ページ/404 #75 
- [x] このサイトについて画面（LP）/about #76 

## 機能一覧

- [x] 記事の更新
- [x] 記事の削除
- [x] ローディングUI
- [x] twitterAPI繋ぎ込み関連
- [x] 各ガード
- [x] テキスト検索（algolia）
- [x] タグ検索（algolia）
- [x] 記事へのいいね
- [x] 関連ツイートの無限スクロール
- [x] メール送信（sendgrid）
